# anythingllm-feeder — extract documents/videos to Markdown (forage) and feed
# a local AnythingLLM (ingest).
#
# Release workflow:
#   1. Tag and push a release on github.com/mschuerig/anythingllm-feeder
#      (e.g. v0.1.0). Update the `url` below.
#   2. Compute the tarball sha256:
#        curl -sL <url> | shasum -a 256
#      and paste it into `sha256`.
#   3. Fill in transitive Python deps:
#        brew update-python-resources Formula/anythingllm-feeder.rb
#      (This walks PyPI for httpx, send2trash, shtab, docling, mlx-whisper and
#      emits one `resource` block per dep + transitive. Re-run on every bump.)
#   4. brew install --build-from-source mschuerig/tap/anythingllm-feeder
#      then `brew audit --strict --new anythingllm-feeder` before publishing.

class AnythingllmFeeder < Formula
  include Language::Python::Virtualenv

  desc "Extract docs/videos to Markdown (forage) and feed AnythingLLM (ingest)"
  homepage "https://github.com/mschuerig/anythingllm-feeder"

  # TODO: replace with the URL of a tagged GitHub release tarball.
  url "https://github.com/mschuerig/anythingllm-feeder/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"

  license "MIT"
  head "https://github.com/mschuerig/anythingllm-feeder.git", branch: "main"

  # mlx-whisper requires Apple Silicon; docling pulls in PyTorch which is
  # heavy but available on macOS arm64 wheels.
  depends_on "ffmpeg"
  depends_on "python@3.12"
  depends_on :macos
  depends_on arch: :arm64

  # ----- Python resources -----
  # Top-level runtime deps as declared in pyproject.toml. `brew
  # update-python-resources` will expand this list with transitive deps
  # (each becomes its own `resource` block with a pinned version + sha256).
  #
  # resource "httpx" do
  #   url "..."
  #   sha256 "..."
  # end
  # resource "send2trash" do ...
  # resource "shtab" do ...
  # resource "docling" do ...        # large; pulls in torch via transitives
  # resource "mlx-whisper" do ...    # Apple Silicon only

  def install
    virtualenv_install_with_resources

    # shtab-generated completions, written via our hidden --print-completion flag.
    generate_completions_from_executable(bin/"forage", "--print-completion",
                                         shells: [:bash, :zsh])
    generate_completions_from_executable(bin/"ingest", "--print-completion",
                                         shells: [:bash, :zsh])

    # Pre-built man pages live under man/ in the source tree (generated by
    # scripts/build_manpages.py; committed so we don't need argparse-manpage
    # in the install-time dependency closure).
    man1.install "man/forage.1", "man/ingest.1"
  end

  def caveats
    <<~EOS
      anythingllm-feeder installs about 3–5 GB of Python packages because
      `docling` brings in PyTorch. `mlx-whisper` requires Apple Silicon.

      Data directory (preserved across `brew upgrade` and `brew uninstall`):
        ~/Library/Application Support/anythingllm-feeder/

      To wipe collections and state before uninstalling, run:
        forage purge          # or:  ingest purge

      Both commands move the data root to Trash; recover via Finder → Trash
      → Put Back. They are synonyms — pick whichever you remember.

      `ingest` expects a local AnythingLLM at http://localhost:3001 and an
      API key in $ANYTHINGLLM_API_KEY. See `man ingest`.

      If things ever look inconsistent (restore from backup, partial state,
      accidental wipe), start with IN_CASE_OF_ERRORS.md in the source repo.
    EOS
  end

  test do
    assert_match "forage", shell_output("#{bin}/forage --help")
    assert_match "ingest", shell_output("#{bin}/ingest --help")
    # Shtab completion: smoke-test the generation path the install step uses.
    assert_match "_shtab_forage", shell_output("#{bin}/forage --print-completion bash")
    assert_match "ingest", shell_output("#{bin}/ingest --print-completion zsh")
  end
end
